general:
  per_page: 10
  size_image: 60x60
models:
  position:
    max_length_name: 150
    max_length_abbreviation: 50
  skill_user:  
    level_inclusion: 1..10  
  user:
    roles:
      - admin
      - user